version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.1.4

jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run: heroku config::set ...
      - run:
          command: >
            "Je vais déployer sur Heroku depuis CircleCI"
      - heroku/deploy-via-git

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/joke-app
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_LOGIN/joke-app
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  node-test:
    jobs:
      - node/test:
          matrix:
            parameters:
              version: ["12.13", "14.19", "16.15"]
          filters:
            branches:
              only: main

      - node/run:
          npm-run: build
          filters:
            branches:
              only: main

      - heroku/deploy-via-git:
          app-name: circleci-cours
          requires:
              - node/test
              - node/run

      - build-and-push:
          requires:
              - node/test
              - node/run