version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run: heroku config::set ...
      - run:
          command: >
            "Je vais déployer sur Heroku depuis CircleCI"
      - heroku/deploy-via-git

workflows:
  node-test:
    jobs:
      - node/test:
          matrix:
            parameters:
              version: ["12.13", "14.19", "16.15"]
          filters:
            branches:
              only: main

      - node/run:
          npm-run: build
          filters:
            branches:
              only: main

      - heroku/deploy-via-git:
          app-name: circleci-cours
          requires:
              - node/test
              - node/run