version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

workflows:
  node-test:
    jobs:
      - node/test:
          matrix:
            parameters:
              version: ["12.13", "14.19", "16.15"]
          filters:
            branches:
              only: main

      - node/run:
          npm-run: build
          filters:
            branches:
              only: main

      - heroku/deploy-via-git:
          app-name: circleci-cours
          requires:
              - node/test
              - node/run